source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'redcarpet'
gem 'jquery-rails'
gem 'bcrypt-ruby'

group :development do
  gem 'sqlite3'
  gem 'faker'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
end
